// src/app/user-edit/user-edit.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, NgForm } from '@angular/forms';

@Component({
  selector: 'app-user-edit',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './user-edit.component.html',
  styleUrl: './user-edit.component.css'
})
export class UserEditComponent {
  @Input() user = { firstName: '', lastName: '', registrationDate: '' };
  @Input() isEditMode = false;
  @Output() save = new EventEmitter<any>();
  @Output() cancelEdit = new EventEmitter<void>();

  today: string = new Date().toISOString().split('T')[0];

  saveUser(form: NgForm) {
    if (form.valid) {
      this.save.emit(this.user);
    } else {
      console.log("Form is invalid");
    }
  }

  cancel() {
    this.cancelEdit.emit();
  }
}

<div class="card mt-3">
    <div class="card-body">
      <h3>{{ isEditMode ? 'Edit User' : 'Add User' }}</h3>
      <form (ngSubmit)="saveUser(userForm)" #userForm="ngForm">
        <div class="mb-3">
          <label for="firstName" class="form-label">First Name</label>
          <input
            [(ngModel)]="user.firstName"
            name="firstName"
            class="form-control"
            id="firstName"
            required
            #firstName="ngModel"
          />
          <div *ngIf="firstName.invalid && firstName.touched" class="text-danger">
            First Name is required.
          </div>
        </div>
        
        <div class="mb-3">
          <label for="lastName" class="form-label">Last Name</label>
          <input
            [(ngModel)]="user.lastName"
            name="lastName"
            class="form-control"
            id="lastName"
            required
            #lastName="ngModel"
          />
          <div *ngIf="lastName.invalid && lastName.touched" class="text-danger">
            Last Name is required.
          </div>
        </div>
        
        <div class="mb-3">
          <label for="registrationDate" class="form-label">Registration Date</label>
          <input
            [(ngModel)]="user.registrationDate"
            name="registrationDate"
            class="form-control"
            type="date"
            id="registrationDate"
            [max]="today"
            required
            #registrationDate="ngModel"
          />
          <div *ngIf="registrationDate.invalid && registrationDate.touched" class="text-danger">
            <div *ngIf="registrationDate.errors?.['required']">Registration Date is required.</div>
            <div *ngIf="registrationDate.errors?.['max']">Date cannot be in the future.</div>
          </div>
        </div>
        
        <button type="submit" class="btn btn-success" [disabled]="userForm.invalid">
          {{ isEditMode ? 'Save Changes' : 'Add User' }}
        </button>
        <p></p>
        <button type="button" class="btn btn-secondary" (click)="cancel()">Cancel</button>
      </form>
    </div>
  </div>

// src/components/UserEdit.tsx
import React, { useState } from 'react';

interface User {
  firstName: string;
  lastName: string;
  registrationDate: string;
}

interface UserEditProps {
  user: User;
  isEditMode: boolean;
  onSave: (user: User) => void;
  onCancel: () => void;
}

const UserEdit: React.FC<UserEditProps> = ({ user, isEditMode, onSave, onCancel }) => {
  const [formData, setFormData] = useState<User>(user);
  const today = new Date().toISOString().split('T')[0];

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <div>
      <h3>{isEditMode ? 'Edit User' : 'Add User'}</h3>
      <form className="user-form" onSubmit={handleSubmit}>
        <div>
          <label htmlFor="firstName">First Name</label>
          <input
            type="text"
            id="firstName"
            name="firstName"
            value={formData.firstName}
            onChange={handleChange}
            required
          />
        </div>
        <div>
          <label htmlFor="lastName">Last Name</label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            value={formData.lastName}
            onChange={handleChange}
            required
          />
        </div>
        <div>
          <label htmlFor="registrationDate">Registration Date</label>
          <input
            type="date"
            id="registrationDate"
            name="registrationDate"
            value={formData.registrationDate}
            onChange={handleChange}
            max={today}
            required
          />
        </div>
        <p></p>
        <button type="submit" disabled={!formData.firstName || !formData.lastName || !formData.registrationDate}>
          {isEditMode ? 'Save Changes' : 'Add User'}
        </button>
        <p></p>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>
    </div>
  );
};

export default UserEdit;
