// src/components/UserList.tsx
import React, { useState } from 'react';
import UserEdit from './UserEdit';

interface User {
  firstName: string;
  lastName: string;
  registrationDate: string;
}

const UserList: React.FC = () => {
  const [users, setUsers] = useState<User[]>([
    { firstName: 'Andrew', lastName: 'Stone', registrationDate: new Date().toISOString().split('T')[0] },
    { firstName: 'Marry', lastName: 'Smith', registrationDate: new Date().toISOString().split('T')[0] },
  ]);

  const [currentUser, setCurrentUser] = useState<User>({ firstName: '', lastName: '', registrationDate: '' });
  const [isEditorVisible, setIsEditorVisible] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  const startAdding = () => {
    setCurrentUser({ firstName: '', lastName: '', registrationDate: new Date().toISOString().split('T')[0] });
    setIsEditMode(false);
    setIsEditorVisible(true);
  };

  const startEditing = (user: User, index: number) => {
    setCurrentUser({ ...user });
    setIsEditMode(true);
    setEditingIndex(index);
    setIsEditorVisible(true);
  };

  const saveUser = (user: User) => {
    if (isEditMode && editingIndex !== null) {
      const updatedUsers = [...users];
      updatedUsers[editingIndex] = user;
      setUsers(updatedUsers);
    } else {
      setUsers([...users, user]);
    }
    cancelEdit();
  };

  const deleteUser = (index: number) => {
    const updatedUsers = users.filter((_, i) => i !== index);
    setUsers(updatedUsers);
  };

  const cancelEdit = () => {
    setIsEditorVisible(false);
    setCurrentUser({ firstName: '', lastName: '', registrationDate: '' });
    setEditingIndex(null);
  };

  return (
    <div className="user-list">
      <button onClick={startAdding}>Add New User</button>
      <table>
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Registration Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user, index) => (
            <tr key={index}>
              <td>{user.firstName}</td>
              <td>{user.lastName}</td>
              <td>{user.registrationDate}</td>
              <td>
                <button onClick={() => startEditing(user, index)}>Edit</button>
                <p></p>
                <button onClick={() => deleteUser(index)}>Delete</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {isEditorVisible && (
        <UserEdit
          user={currentUser}
          isEditMode={isEditMode}
          onSave={saveUser}
          onCancel={cancelEdit}
        />
      )}
    </div>
  );
};

export default UserList;

// src/app/user-list/user-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UserEditComponent } from '../user-edit/user-edit.component';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [CommonModule, UserEditComponent],
  templateUrl: './user-list.component.html',
  styleUrl: './user-list.component.css'
})
export class UserListComponent {
  users = [
    { firstName: 'Andrew', lastName: 'Stone', registrationDate: new Date().toISOString().split('T')[0] },
    { firstName: 'Marry', lastName: 'Smith', registrationDate: new Date().toISOString().split('T')[0] },
  ];

  currentUser: any = null;
  isEditorVisible = false;
  isEditMode = false;
  editingIndex: number | null = null;

  startAdding() {
    this.currentUser = { firstName: '', lastName: '', registrationDate: new Date().toISOString().split('T')[0] };
    this.isEditMode = false;
    this.isEditorVisible = true;
  }

  startEditing(user: any, index: number) {
    this.currentUser = { ...user };
    this.isEditMode = true;
    this.editingIndex = index;
    this.isEditorVisible = true;
  }

  saveUser(user: any) {
    if (this.isEditMode && this.editingIndex !== null) {
      this.users[this.editingIndex] = user;
    } else {
      this.users.push(user);
    }
    this.cancelEdit();
  }

  deleteUser(index: number) {
    this.users.splice(index, 1);
  }

  cancelEdit() {
    this.isEditorVisible = false;
    this.currentUser = null;
    this.editingIndex = null;
  }
}
<div class="user-list">
    <button (click)="startAdding()">Add New User</button>
    
    <table>
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Registration Date</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let user of users; let i = index">
          <td>{{ user.firstName }}</td>
          <td>{{ user.lastName }}</td>
          <td>{{ user.registrationDate | date }}</td>
          <td>
            <button (click)="startEditing(user, i)">Edit</button>
            <p></p>
            <button (click)="deleteUser(i)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
  
    <app-user-edit
      *ngIf="isEditorVisible"
      [user]="currentUser"
      [isEditMode]="isEditMode"
      (save)="saveUser($event)"
      (cancelEdit)="cancelEdit()"
    ></app-user-edit>
  </div>
