// src/components/user/UserList.tsx
import React, { useState } from 'react';
import UserEdit from './UserEdit';
import { AppUser, Role } from '../../models/AppUser';

interface UserListProps {
  users: AppUser[];
  roles: Role[];
  onAddUser: (user: AppUser) => void;
  onEditUser: (user: AppUser, index: number) => void;
  onDeleteUser: (index: number) => void;
}

const UserList: React.FC<UserListProps> = ({ users, roles, onAddUser, onEditUser, onDeleteUser }) => {
  const [currentUser, setCurrentUser] = useState<AppUser>({
    id: 0,
    username: '',
    firstname: '',
    surname: '',
    email: '',
    phone_num: '',
    enc_password: '',
    avatar: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    roles: [],
    isBanned: false,
  });
  const [isEditorVisible, setIsEditorVisible] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  const startAdding = () => {
    setCurrentUser({
      id: Date.now(),
      username: '',
      firstname: '',
      surname: '',
      email: '',
      phone_num: '',
      enc_password: '',
      avatar: '',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      roles: [],
      isBanned: false,
    });
    setIsEditMode(false);
    setIsEditorVisible(true);
  };

  const startEditing = (user: AppUser, index: number) => {
    setCurrentUser({ ...user });
    setIsEditMode(true);
    setEditingIndex(index);
    setIsEditorVisible(true);
  };

  const saveUser = (user: AppUser) => {
    if (isEditMode && editingIndex !== null) {
      onEditUser(user, editingIndex);
    } else {
      onAddUser(user);
    }
    setIsEditorVisible(false);
  };

  const cancelEdit = () => {
    setIsEditorVisible(false);
  };

  const toggleBanUser = (index: number) => {
    const updatedUsers = [...users];
    updatedUsers[index].isBanned = !updatedUsers[index].isBanned;
    onEditUser(updatedUsers[index], index);
  };

  return (
    <div className="user-list">
      <button onClick={startAdding}>Add New User</button>
      <table>
        <thead>
          <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user, index) => (
            <tr key={user.id}>
              <td>{user.username}</td>
              <td>{user.firstname}</td>
              <td>{user.surname}</td>
              <td>{user.email}</td>
              <td>{user.phone_num}</td>
              <td data-status={user.isBanned ? "banned" : "active"}>
                {user.isBanned? "Banned" : "Active"}
              </td>
              <td>
                <button onClick={() => startEditing(user, index)}>Edit</button>
                <button onClick={() => toggleBanUser(index)}>
                  {user.isBanned ? "Unban" : "Ban"}
                </button>
                <button onClick={() => onDeleteUser(index)}>Delete</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {isEditorVisible && (
        <UserEdit
          user={currentUser}
          roles={roles}
          isEditMode={isEditMode}
          onSave={saveUser}
          onCancel={cancelEdit}
        />
      )}
    </div>
  );
};

export default UserList;

// src/app/user-list/user-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UserEditComponent } from '../user-edit/user-edit.component';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [CommonModule, UserEditComponent],
  templateUrl: './user-list.component.html',
  styleUrl: './user-list.component.css'
})
export class UserListComponent {
  users = [
    { firstName: 'Andrew', lastName: 'Stone', registrationDate: new Date().toISOString().split('T')[0] },
    { firstName: 'Marry', lastName: 'Smith', registrationDate: new Date().toISOString().split('T')[0] },
  ];

  currentUser: any = null;
  isEditorVisible = false;
  isEditMode = false;
  editingIndex: number | null = null;

  startAdding() {
    this.currentUser = { firstName: '', lastName: '', registrationDate: new Date().toISOString().split('T')[0] };
    this.isEditMode = false;
    this.isEditorVisible = true;
  }

  startEditing(user: any, index: number) {
    this.currentUser = { ...user };
    this.isEditMode = true;
    this.editingIndex = index;
    this.isEditorVisible = true;
  }

  saveUser(user: any) {
    if (this.isEditMode && this.editingIndex !== null) {
      this.users[this.editingIndex] = user;
    } else {
      this.users.push(user);
    }
    this.cancelEdit();
  }

  deleteUser(index: number) {
    this.users.splice(index, 1);
  }

  cancelEdit() {
    this.isEditorVisible = false;
    this.currentUser = null;
    this.editingIndex = null;
  }
}
<div class="user-list">
    <button (click)="startAdding()">Add New User</button>
    
    <table>
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Registration Date</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let user of users; let i = index">
          <td>{{ user.firstName }}</td>
          <td>{{ user.lastName }}</td>
          <td>{{ user.registrationDate | date }}</td>
          <td>
            <button (click)="startEditing(user, i)">Edit</button>
            <p></p>
            <button (click)="deleteUser(i)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
  
    <app-user-edit
      *ngIf="isEditorVisible"
      [user]="currentUser"
      [isEditMode]="isEditMode"
      (save)="saveUser($event)"
      (cancelEdit)="cancelEdit()"
    ></app-user-edit>
  </div>
